### ISSUE TITLE
If patching a romhack...

### ISSUE THREAD

**Issue by MetaSamsara** [choogiesaur/hgss-shiny-modifier#3]
If patching a romhack such as Sacred Gold and Storm Silver, should I edit the .nds file before or after patching it with the xdelta patch? Maybe it doesn't matter?

**Comment by MattTheCrazyCat** [comment]
Hey, I'm not sure what would be recommended by the developer. But I
believe I've done it both ways with success. My recommendation would apply
your patch first, and test a couple times it may not work right away.

**Comment by MetaSamsara** [comment]
Yeah i noticed after this that xdelta would give me troubles patching if it isn't the exact rom with exact checksum unless I bypass, but if I bypass it corrupts it? Regardless of order though my 3DS won't play it :/ Twilight Menu++ just freezes on white screen.

**Comment by MetaSamsara** [comment]
After a good night of sleep and further testing, the game launches fine every step of the way without shiny patch (US rom on EU console>xdelta patched rom), but when I patch the shiny script onto it, the rom won't launch. I've tested both (xdelta patched rom+shiny script>unpatched US rom+shiny script) and it appears the problem is in both cases the shiny script itself.

Could it be because when I installed the script dependency, I got a warning message telling me that the python directory is not added to Windows' PATH? I don't know much about this stuff but I've also installed Stable Diffusion and it wouldn't work until I did a specific edit of a PATH directory so unless it is different, it should already be setup.

Here's some screenshots of the script compilations for both default rom and hackrom:
HeartGold: https://i.imgur.com/jaraZKy.png
SacredGold: https://i.imgur.com/aAqftEv.png

And for good measure here's my environment variables window:
https://i.imgur.com/3VrakCp.png

Hopefully that helps pinpoint the issue.
PS: I've updated my Twilight Menu++ to latest version before testing thoroughly.

**Comment by MetaSamsara** [comment]
Update to say I managed to successfully hack the shiny rate manually by loading the rom into DSPRE and editing the arm9.bin hex value manually, then clicking on yes when saving the rom back in DSPRE with the warning about uncompressed arm9.bin file. So I know it is possible to get it working on my 3DS now, the issue is with the python script in itself. It seems it is a similar issue as with the other issue about patching a French rom someone else raised on this github repo.

**Comment by choogiesaur** [comment]
Hi @NeonSpaceTurtle . So the way the script works, it goes to a predetermined offset where we know the shiny encounter rate is located in clean roms. So if you had patched your rom beforehand with a romhack, if the offset is no longer in the same place (quite likely given that romhacks change a lot of the contents), it wouldn't work.

You would have to figure out where the new shiny encounter offset is in your modded rom which people do with an emu/cheat code debugger or hex editor. [See this](https://projectpokemon.org/home/forums/topic/59297-shiny-rate-offset-for-all-generation-4-pokemon-roms/)

Also since this script uses NDSPY and the arm9 recompression does not generate an exact 1-to-1 copy of the original, it makes it unlikely that an xdelta patch could be applied as the resultant rom is different from a clean rom. EDIT: I spoke mistakenly, the script does not recompress but reinserts the arm9 uncompressed.

Sorry there isn't better news, I may try and look into solutions for this when I have time.

**Comment by MetaSamsara** [comment]
> Hi @NeonSpaceTurtle . So the way the script works, it goes to a predetermined offset where we know the shiny encounter rate is located in clean roms. So if you had patched your rom beforehand with a romhack, if the offset is no longer in the same place (quite likely given that romhacks change a lot of the contents), it wouldn't work.
> 
> You would have to figure out where the new shiny encounter offset is in your modded rom which people do with an emu/cheat code debugger or hex editor. [See this](https://projectpokemon.org/home/forums/topic/59297-shiny-rate-offset-for-all-generation-4-pokemon-roms/)
> 
> Also since this script uses NDSPY and the arm9 recompression does not generate an exact 1-to-1 copy of the original, it makes it unlikely that an xdelta patch could be applied as the resultant rom is different from a clean rom.
> 
> Sorry there isn't better news, I may try and look into solutions for this when I have time.

That's the thing I have the same issue with a clean rom it doesn't come from the romhack replacing the offset. I was able to patch it manually through different tools as mentioned and it works. I think there is an issue with how arm9 is recompressed into the rom because I used the same offsets when doing it manually.

**Comment by choogiesaur** [comment]
@NeonSpaceTurtle Oh yeah- the arm9 is actually not recompressed. It's decompressed, modified, then reinserted uncompressed. 
This was done because at the time recompression was causing the game to crash randomly. Not sure if this is still the case with NDSPY. Again will have to look into it later. If anyone has ideas though, please comment them here.

**Comment by SunOfLife1** [comment]
I actually just now forked this repository to fix this very issue with a ROM hack, Pokemon Soothing Silver. The issue, from what I can tell, is that the arm9 is not recompressed but is marked as compressed. I fixed it by adding the following code after the shiny rate is changed: 
```python
# Mark the arm9 as uncompressed
decompressed_arm9[0xBB4] = 0x00
decompressed_arm9[0xBB5] = 0x00
decompressed_arm9[0xBB6] = 0x00
decompressed_arm9[0xBB7] = 0x00
```

Edit: The above offsets are for a European SoulSilver ROM. I'm fairly certain they're the same for all NDS ROMs, but I'm adding this note just in case I'm mistaken.

**Comment by choogiesaur** [comment]
Thanks @digikitty21 ! Would you mind making a pull request with this and your hex output change? I would like to give you credit :) If not and you don’t mind, I’ll manually add the changes to my repo.

**Comment by choogiesaur** [comment]
Should be fixed by [this pr](https://github.com/choogiesaur/hgss-shiny-modifier/pull/5). If anyone encounters issue comment here
